views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Product, Item, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db

# # This data will eventually be stored in a database
# milk = Product('1', 'Milk', 'Perfect milk for your daily essentials.', 'milkImg1.jpg')
# vitamin = Product('2', 'Vitamin', 'Nutrients for a wonderful life style.', 'vitaminImg2.jpg')
# item1 = Item('1', 'A2 Milk powder 1kg', 'Premium branded dairy nutritional company uniquely focused on products containing the A2 beta-casein protein type.', 'a2milk.png', 100.45, milk, datetime(2020,7,23))
# item2 = Item('2', 'Nestle Milo 1kg', 'A nutrient rich, low GI drink which gives kids the nourishing energy they need to take on the day.', 'milo.jpg', 200.00, milk, datetime(2019,10,30))
# item3 = Item('3', 'Progetic Vitamin D3', 'Visit Straddy and see the whales migrating', 'vitaminD3.jpg', 30.00, vitamin, datetime(2019,10,30))
# products = [milk, vitamin]
# items = [item1,item2,item3]
# order1 = Order('1', False, '', '','', '', datetime.now(), [item1, item2], item1.price+item2.price) # simulating order not checked out
# order2 = Order('2', False, '', '','', '', datetime.now(), [item1, item3], item1.price+item3.price) # simulating order not checked out
# orders = [order1,order2]

bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    products = Product.query.order_by(Product.name).all()
    return render_template('index.html', products = products)

@bp.route('/about')
def about():
    return render_template('aboutus.html')

@bp.route('/items/')
def search():
    search = request.args.get('search')
    search = '%{}%'.format(search)
    items = Item.query.filter(Item.description.like(search)).all()
    return render_template('productItems.html', items = items)

@bp.route('/items/<int:productid>/')
# def productItems(productid):
#     productItems = []
#     # create list of items for this product
#     for item in items:
#             if int(item.product.id) == int(productid): 
#                 productItems.append(item)
#     return render_template('productItems.html', items = productItems)

def productItems(productid):
    items = Item.query.filter(Item.product_id == productid)
    return render_template('productItems.html', items = items)

# Referred to as "Basket" to the user
@bp.route('/order/', methods=['POST','GET'])
# def order():

#     item_id = request.args.get('item_id')
#     # is this a new order?
#     if 'order_id'not in session:
#         session['order_id'] = 1 # arbitry, we could set either order 1 or order 2
    
#     #retrieve correct order object
#     for x in orders:
#             if int(x.id) == int(session['order_id']): 
#                 order = x
#     # are we adding an item? - will be implemented later with DB
#     if item_id:
#         print('user requested to add item id = {}'.format(item_id))

#     return render_template('order.html', order = order, totalprice = order.total_cost)

def order():
    item_id = request.values.get('item_id')

    # retrieve order if there is one
    if 'order_id'in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None
    
    # create new order if needed
    if order is None:
        order = Order(status = False, firstname='', surname='', email='', phone='', totalcost=0)
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # calcultate totalprice
    totalprice = 0
    if order is not None:
        for item in order.items:
            totalprice = totalprice + item.price

    # are we adding an item?
    if item_id is not None and order is not None:
        item = Item.query.get(item_id)
        if item not in order.items:
            try:
                order.items.append(item)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('item already in basket')
            return redirect(url_for('main.order'))

    return render_template('order.html', order = order, totalprice = totalprice)

# @bp.route('/deleteorder/')
# def deleteorder():
#     if 'order_id' in session:
#         del session['order_id']
#     return render_template('index.html')

# @bp.route('/deleteorderitem/', methods=['POST'])
# def deleteorderitem():
#     print('User wants to delete item with id={}'.format(request.form['id']))
#     return render_template('index.html')

# Delete specific basket items
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        item_to_delete = Item.query.get(id)
        try:
            order.items.remove(item_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# Scrap basket
@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))



@bp.route('/checkout/', methods=['POST','GET'])
#def checkout():
    # form = CheckoutForm() 
    # if 'order_id' in session:
        
    #     #retrieve correct order object
    #     for x in orders:
    #             if int(x.id) == int(session['order_id']): 
    #                 order = x
       
    #     if form.validate_on_submit():
    #         order.status = True
    #         order.firstname = form.firstname.data
    #         order.surname = form.surname.data
    #         order.email = form.email.data
    #         order.phone = form.phone.data
    #         print(order)
    #         flash('Thank you for your information')

    # return render_template('checkout.html', form = form)
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
       
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            totalcost = 0
            for item in order.items:
                totalcost = totalcost + item.price
            order.totalcost = totalcost
            #order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you! One of our awesome team members will contact you soon...')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form = form)

templates/aboutus.html
{% extends 'base.html' %}

{% block main %}
<section>
    <div class="container text-center" style="padding-top: 20px">
        <div class="text-white text-center">
            <div><img src="static/img/AboutUs.jpg" class="img-fluid text-center" alt="image" style="width: 100%; padding-bottom: 10px;"></div>
            <div>
                <p class="h1 text-dark mb-4">ABOUT US</p>
            </div>
        </div>
        <div class="text-center">
            <div>
                <p class="h4 text-dark mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam felis erat, auctor ac dui eget, suscipit pharetra lorem. Aenean felis justo, suscipit vel dui eget, posuere bibendum ligula. Quisque tincidunt porta diam, vel aliquam orci. Ut vehicula, risus at bibendum sollicitudin, urna turpis faucibus sapien, nec porttitor ante lorem et elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam felis erat, auctor ac dui eget, suscipit pharetra lorem. Aenean felis justo, suscipit vel dui eget, posuere bibendum ligula. Quisque tincidunt porta diam, vel aliquam orci. Ut vehicula, risus at bibendum sollicitudin, urna turpis faucibus sapien, nec porttitor ante lorem et elit.</p>

                <p class="h4 text-dark mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam felis erat, auctor ac dui eget, suscipit pharetra lorem. Aenean felis justo, suscipit vel dui eget, posuere bibendum ligula. Quisque tincidunt porta diam, vel aliquam orci. Ut vehicula, risus at bibendum sollicitudin, urna turpis faucibus sapien, nec porttitor ante lorem et elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam felis erat, auctor ac dui eget, suscipit pharetra lorem. Aenean felis justo, suscipit vel dui eget, posuere bibendum ligula. Quisque tincidunt porta diam, vel aliquam orci. Ut vehicula, risus at bibendum sollicitudin, urna turpis faucibus sapien, nec porttitor ante lorem et elit.</p>
            </div>
        </div>               
    </div>
</section>

<!--Partners-->
<section class="container">
    <div class="text-center" style="padding-top: 20px">
        <h2 class="h1 text-dark mb-4">Our partners</h2>
    </div>
    <div class="container" style="padding-top: 20px">
        <div class="row row-cols-1 row-cols-md-3">
            <div class="col mb-4">
                <div class="card">
                  <img src="static/img/bootstraplogo.png" class="card-img-top mx-auto d-block" style="width:200px" alt="bstrap4">                        
                </div>
            </div>
            <div class="col mb-4">
              <div class="card">
                <img src="static/img/minervalogo.png" class="card-img-top mx-auto d-block" style="width:200px" alt="minerva">                        
              </div>
            </div>
            <div class="col mb-4">
              <div class="card">
                <img src="static/img/a2logo.png" class="card-img-top mx-auto d-block" style="width:200px" alt="a2">                   
              </div>
            </div>
            <div class="col mb-4">
              <div class="card">
                <img src="static/img/nestlelogo.png" class="card-img-top mx-auto d-block" style="width:200px" alt="nestle">                    
              </div>
            </div>           
        </div>
    </div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>The GreenyFarm</title>
    <meta name="description" content="The GreenFarm for life">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- an example of using css alongside bootstrap -->
    <style>
        /* to place border around items in the shopping basket - orders.html */
        .my-row {
            border: 1px solid grey;
        }

        .jumbotron {
            min-height: 600px;
        }
}
    </style>
</head>

<body>
    <!-- putting header inside container will prevent full width navbar -->
    <div class="text-center text-white font-italic" style="background-color: rgb(100, 99, 99);">Ahoy! - We are among the top international agricultural solution providers - Call us: +61 123456789</div>
    <header>

        <!--navbar creates a navigation bar -->
        <!-- Colours https://getbootstrap.com/docs/4.0/utilities/colors/ -->

        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: darkgreen;">

            <a class="navbar-brand text-light font-weight-bolder" href="{{ url_for('main.index') }}">
                <img src="{{url_for('static', filename='img/logo.jpg')}}" width="35" height="35" class="d-inline-block align-top"
                    alt="Site Logo" loading="lazy">
                THE GREENYFARM
            </a>

            <!-- create a button for collapsing the menu -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <!-- individual menu item-->
                <a class="nav-item nav-link text-light active" href="{{url_for('main.about')}}">About Us</a>

                <!-- individual menu item-->
                <a class="nav-item nav-link text-light" href="{{url_for('main.index', _anchor='products_anchor')}}">Our products</a>

                <!-- individual menu item-->
                <a class="nav-item nav-link text-light" href="{{url_for('main.order')}}">Basket</a>

                <!-- individual menu item-->
                <!-- this link will fail but good test of the 404 handler -->
                <a class="nav-item nav-link text-light" href="discounts.html">Offers</a>

                <!-- right aligned menu items thanks to ml-auto -->
                <ul class="nav navbar-nav ml-auto">                   
                    <li class="nav-item">
                        <!-- search box -->
                        <form class="form-inline my-2 my-lg-0 ml-5" action ="{{url_for('main.search')}}">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search">
                            <button class="btn btn-outline-black btn btn-secondary btn-s my-0 ml-1"
                                type="submit">Search</button>
                        </form>
                    </li>
                </ul>

        </nav>
        
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-primary" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %} 

        {% block head %}{% endblock %}

    </header>


    <!-- main page content goes in container -->
    <div class="container-fluid" style="padding-bottom: 20px;">
        <main>
            {% block main %}{% endblock %}
        </main>
    </div>

    
    <!-- Footer -->
    <footer class="footer">
        <div class="text-center text-white" style="background-color: rgb(100, 99, 99);">
            <p>Copyright &copy; sem5D 2020 IFN557</p>
        </div>
    </footer>
    <!-- Footer -->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        </div>
    {% endif %}
    {% endwith %} 
{% endblock %}

{% block main %}
    <section>  
        <div class="container">
            <div class="row">
                <div class = "col-12">
                    <h1>Checkout</h1>
                    <p>
                        Thank you for your interest. Please provide your details so that we can contact you to finalise details and take payment. Thank you! 
                    </p>
                </div>
            </div>
            <div class="row">
                <div class = "col-6">
                    {{wtf.quick_form(form)}}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block head %}
<!-- add a big banner to welcome user -->
<div class="jumbotron jumbotron-fluid card card-image" style="background-image: url({{url_for('static', filename='img/bannermain.jpg')}});">
    <div class="text-white text-center py-5 px-4">
        <div>
            <h1 class="display-2 text-monospace font-weight-bolder">Welcome to The GreenyFarm</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<!-- marketing information -->
<section>
    <div class="container" style="padding-bottom;">
        <div class="text-white text-center">
            <div>
                <p class="h1 text-dark mb-4">Why us?</p>
            </div>
        </div>
        <div class="text-center">
            <div>
                <p class="h4 text-dark mb-4">We are a growing nutrients distributor and consulting global business actively facilitating the provision of high quality agricultural solutions & natural products to the world.</p>
                <p>We have <span> great prices and offers </span> all year round!</p>
                <p>Click <a href="offers.html">here</a> for more information.</p>
            </div>
        </div>       
        <!-- Horizontal Rule -->
        <hr>
    </div>
</section>

<!-- display the main product lines to the user -->
<section>
    <div class="text-dark text-center">
        <div>
            <p class="h3 text-dark mb-4" id="products_anchor" style="padding-top: 20px">Pick a product line to see what we have to offer!</p>
        </div>
    </div>
    <div class="card-deck">

        {% for product in products%}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+product.image)}}" alt="Card image">
            <div class="card-body">                
                <h4 class="card-title">{{product.name}}</h4>
                <p class="card-text">{{product.description}}</p>
            </div>
            <div class="card-footer">
                <a href= "{{ url_for('main.productItems', productid=product.id) }}" class="btn btn-primary">Explore available products!</a>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

<!--Youtube video for the web app demonstration-->
<div class="container" style="padding-top: 40px;">
    <div style="text-align:center"> 
        <button onclick="playPause()">Play/Pause</button> 
        <button onclick="makeBig()">Bigger view</button>
        <button onclick="makeSmall()">Smaller view</button>
        <button onclick="makeNormal()">Normal</button>
        <br><br>
        <video id="video1" width="480">
          <source src="static\img\recording.mp4" type="video/mp4" alt=""introduction video""></video>
      </div> 
      
      <script> 
      var myVideo = document.getElementById("video1"); 
      
      function playPause() { 
        if (myVideo.paused) 
          myVideo.play(); 
        else 
          myVideo.pause(); 
      } 
      
      function makeBig() { 
          myVideo.width = 800; 
      } 
      
      function makeSmall() { 
          myVideo.width = 320; 
      } 
      
      function makeNormal() { 
          myVideo.width = 480; 
      } 
      </script> 
      
      <p class="text-center">Link <a href="https://youtu.be/Klrj2FsVk7E" target="_blank">Youtube video</a> for the web app.</p>
</div>

{% endblock %}

templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>  
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h3>Shopping Basket</h3>
        </div>
        <!-- each tour on seperate row -->
        {% for item in order.items %}
            <div class="row shadow-md my-row mb-3">
                <div class="col-sm-10 card">
                    <h5 class="card-header">{{item.Product.name}} {{item.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + item.image))}}">
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->
                                <p class="card-text">{{item.description}}</p>   
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                    <!-- delete item button -->
                        <h5>{{ "$%.2f"|format(item.price) }}</h5>
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="{{item.id}}">
                            <input type="submit" value="Delete" class="btn btn-primary mb-3">
                        </form> 
                </div>
            </div>
        {% endfor %}
        
        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4">Quote = {{ "$%.2f"|format(totalprice) }}</h5>
            </div>
        
            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{ url_for('main.index', _anchor='products_anchor') }}" class="btn btn-primary mr-4">Products</a>
                <a href="{{ url_for('main.checkout') }}" class="btn btn-primary mr-4">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-primary">Empty Basket</a>
            </div>
        </section>
    </div>
</section>
{% endblock %}


templates/productItems.html
{% extends 'base.html' %}

{% block main %}
<!-- display tours for the specific city -->
<section>

    <div class="text-dark text-center" style="padding-top: 20px;">
        <div>
            <p class="h3 text-dark mb-4">Select a product from below</p>
        </div>
    </div>

    <div class="card-columns">
        <!-- each item is a bootstrap card -->
        {% for item in items%}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+item.image)}}" style="max-width: 150px;" alt="product image">
            <div class="card-body">
                <h4 class="card-title">{{item.name}}</h4>
                <p class="card-text">{{item.description}}</p>
                <p class="card-text" style="color: rgb(156, 0, 0);">$AUD{{item.price}}</p>
            </div>
            <div class="card-footer"><a href="{{ url_for('main.order', item_id=item.id) }}" class="btn btn-primary">Add to Basket</a></div>
        </div>
        {% endfor %}
    </div>

</section>
{% endblock %}
